# Generated by Django 4.2.3 on 2023-07-05 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tipoUsuario',
            fields=[
                ('idTipoUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('tipoUsuario', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('appPaterno', models.CharField(max_length=30)),
                ('appMaterno', models.CharField(max_length=30)),
                ('correo', models.EmailField(max_length=100, unique=True)),
                ('cotraseña', models.CharField(max_length=50)),
                ('activo', models.IntegerField()),
            ],
        ),
    ]
